# Generated by Django 3.1.5 on 2021-04-08 09:23

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutinfo',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
